name: GLideN64

on: [push, pull_request, workflow_dispatch]

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        image: ["GLideN64 (x64 Mupen64Plus-Qt)"]
    env:
      QT_VERSION: "6.5.0"  # Specify the Qt6 version
      QT_HOST: "windows"   # Host platform
      QT_TARGET: "desktop" # Target platform
      QT_ARCH: "win64_msvc2019_64"  # Architecture for Qt6
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python for aqtinstall
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Qt6 using aqtinstall
        run: |
          echo "Doctor House: 'Installing Qt6... This better work.'"
          pip install aqtinstall
          aqt list-qt ${{ env.QT_HOST }} ${{ env.QT_TARGET }} --modules ${{ env.QT_VERSION }} ${{ env.QT_ARCH }}  # List available modules
          aqt install-qt ${{ env.QT_HOST }} ${{ env.QT_TARGET }} ${{ env.QT_VERSION }} ${{ env.QT_ARCH }} -m qtbase qttools qttranslations

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            git

      - name: Print Qt Version
        run: |
          echo "Doctor House: 'Let's see what version of Qt we're dealing with...'"
          $QTDIR = "C:\Qt\${{ env.QT_VERSION }}\${{ env.QT_ARCH }}"
          & "$QTDIR\bin\qmake.exe" --version
        shell: pwsh

      - name: Prepare Environment
        run: |
          echo "Doctor House: 'Preparing the environment...'"
          $env:revision = git rev-parse --short HEAD
          echo "PJ64PluginsDirQT=$pwd\build\windows-project64-qt\" >> $env:GITHUB_ENV
          echo "PJ64PluginsDirQT_x64=$pwd\build\windows-project64-qt-x64\" >> $env:GITHUB_ENV
          echo "Mupen64PluginsDir=$pwd\build\windows-mupen64plus-cli\" >> $env:GITHUB_ENV
          echo "Mupen64PluginsDir_x64=$pwd\build\windows-mupen64plus-cli-x64\" >> $env:GITHUB_ENV
          echo "GIT_REVISION=$env:revision" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build GLideN64 (x64 Mupen64Plus-Qt)
        if: ${{ matrix.image == 'GLideN64 (x64 Mupen64Plus-Qt)' }}
        run: |
          echo "Doctor House: 'Building GLideN64 for Mupen64Plus-Qt x64...'"
          $QTDIR = "C:\Qt\${{ env.QT_VERSION }}\${{ env.QT_ARCH }}"
          mkdir -p build/windows-mupen64plus-qt
          pushd build/windows-mupen64plus-qt
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DMUPENPLUSAPI=1 -DMUPENPLUSAPI_GLIDENUI=1 -DDEBUG_DUMP=ON -DCMAKE_PREFIX_PATH="$QTDIR" ../../src
          cmake --build . --config Release --parallel
          popd
          cp ini/GLideN64_sceneripper.custom.ini build/windows-mupen64plus-qt/
          cp translations/release/*.qm build/windows-mupen64plus-qt/
        shell: pwsh

      - name: Upload GLideN64 (x64 Mupen64Plus-Qt)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.image == 'GLideN64 (x64 Mupen64Plus-Qt)' }}
        with:
          name: GLideN64-${{ env.GIT_REVISION }}-Windows-Mupen64Plus-Qt-x64
          path: |
            build\windows-mupen64plus-qt\*.dll
            build\windows-mupen64plus-qt\GLideN64_sceneripper.custom.ini
            build\windows-mupen64plus-qt\*.qm

  Release:
    runs-on: ubuntu-latest
    needs: [Windows]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Re-Package Artifacts
        run: |
          echo "Doctor House: 'Re-packaging artifacts...'"
          cd artifacts
          for artifact in *
          do
            echo "-> Creating ${artifact}.zip"
            pushd "$artifact"
            zip -r "../${artifact}.zip" *
            popd
          done

      - name: Update Git Tag
        run: |
          echo "Doctor House: 'Updating Git tag...'"
          git tag -f github-actions
          git push -f origin github-actions

      - name: Create Release
        uses: ncipollo/release-action@v2
        with:
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: false
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          tag: github-actions
          artifacts: "artifacts/*.zip"
